name: transcendence

x-base: &base
  env_file:
    - .env
  networks:
    - transcendence
  volumes:
    - vault-ca:/ca
  restart: unless-stopped
  init: true

x-micro: &micro
  <<: *base
  healthcheck:
    test: [ "CMD-SHELL", "python manage.py health_check || exit 1" ]
    interval: 2s
    timeout: 2s
    retries: 5
    start_period: 5s
  volumes:
    - static-files:/static
    - media-files:/media

x-db: &db
  <<: *base
  healthcheck:
    test: [ "CMD-SHELL", "pg_isready" ]
    interval: 10s
    timeout: 5s
    retries: 5
  image: postgres
  shm_size: 128mb

services:
  nginx:
    <<: *base
    container_name: nginx
    build:
      context: frontend
    develop:
      watch:
        - action: sync+restart
          path: ./frontend
          target: /usr/share/nginx/html
    volumes:
      - media-files:/media
      - static-files:/static
      - ssl-keys:/etc/ssl
    ports:
      - "80:80"
      - "443:443"
  vault:
    <<: *base
    container_name: vault
    build:
      context: vault
    cap_add:
      - IPC_LOCK
    command: ["vault", "server", "-config=/vault/config/config.hcl"]
    volumes:
      - vault-config:/vault/config
      - vault-data:/vault/file
      - vault-pki:/vault/pki
      - vault-ssl:/vault/ssl
  vault-init:
    <<: *base
    container_name: vault-init
    command: ["sh", "-c", "/vault/scripts/init.sh"]
    depends_on:
      vault:
        condition: service_started
    image: hashicorp/vault:1.17
    restart: no
    volumes:
      - ./vault/scripts:/vault/scripts
      - vault-pki:/vault/pki
      - vault-secrets:/vault/secrets
      - vault-ssl:/vault/ssl
  auth:
    <<: *micro
    container_name: auth
    build:
      context: backend
      args:
        APP_NAME: auth
        HOST: ${HOSTNAME}
    depends_on:
      auth-db:
        condition: service_healthy
    develop:
      watch:
        - action: sync+restart
          path: ./backend/auth/
          target: /auth/
    env_file:
      - auth.env
      - .env
  auth-db:
    <<: *db
    container_name: auth-db
    env_file:
      - auth.env
    volumes:
      - auth-db:/var/lib/postgresql/data
  pong:
    <<: *micro
    container_name: pong
    build:
      context: backend
      args:
        APP_NAME: pong
        HOST: ${HOSTNAME}
    depends_on:
      pong-db:
          condition: service_healthy
    develop:
      watch:
        - action: sync+restart
          path: ./backend/pong/
          target: /pong/
    env_file:
      - pong.env
      - .env
  pong-db:
    <<: *db
    container_name: pong-db
    env_file:
      - pong.env
    volumes:
      - pong-db:/var/lib/postgresql/data

networks:
  transcendence:
    name: transcendence
    driver: bridge

volumes:
  auth-db:
  media-files:
  pong-db:
  static-files:
  vault-ca:
  vault-config:
  vault-data:
  vault-pki:
  vault-secrets:
  vault-ssl: