name: transcendence

x-base: &base
  env_file:
    - .env
  networks:
    - transcendence
  restart: unless-stopped
  init: true

x-micro: &micro
  <<: *base
  healthcheck:
    test: [ "CMD-SHELL", "python manage.py healthcheck || exit 1" ]
    interval: 2s
    timeout: 2s
    retries: 5
    start_period: 5s
  volumes:
    - ssl-keys:/etc/ssl
    - static-files:/static
    - media-files:/media

services:
  nginx:
    <<: *base
    container_name: nginx
    build:
      context: frontend
    develop:
      watch:
        - action: sync+restart
          path: ./frontend
          target: /usr/share/nginx/html
    volumes:
      - ssl-keys:/etc/ssl
      - static-files:/static
      - media-files:/media
    ports:
      - "80:80"
      - "443:443"
  auth:
    <<: *micro
    container_name: auth
    build:
      context: backend
      args:
        APP_NAME: auth
        HOST: ${HOSTNAME}
    develop:
      watch:
        - action: sync+restart
          path: ./backend/auth/
          target: /auth/
  pong:
    <<: *micro
    container_name: pong
    build:
      context: backend
      args:
        APP_NAME: pong
        HOST: ${HOSTNAME}
    develop:
      watch:
        - action: sync+restart
          path: ./backend/pong/
          target: /pong/

networks:
  transcendence:
    name: transcendence
    driver: bridge

volumes:
  ssl-keys:
    driver: local
  static-files:
    driver: local
  media-files:
    driver: local